version: '3'

services:
  db:
    image: mdillon/postgis:9.6
  web:
    build: .
    volumes:
      - .:/code
      - ~/.ssh/tagging_tracker/:/application_keys/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    env_file:
      - local.env
